config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/john-shepherdson/github-markup-scanner:
      branch: main
      repo: https://github.com/john-shepherdson/github-markup-scanner.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/john-shepherdson/github-markup-scanner git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-crimson-mammoth.sh
        container: qc.acc_sickly-plum-macaw
  QC.Doc:
    repos:
      github.com/john-shepherdson/github-markup-scanner find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-periwinkle-dodo.sh
        container: qc.doc_sleazy-periwinkle-beaver
      github.com/john-shepherdson/github-markup-scanner git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cardinal-orangutan.sh
        container: qc.doc_surly-goldenrod-fox
      github.com/john-shepherdson/github-markup-scanner markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-denim-beaver.sh
        container: qc.doc_boozy-pumpkin-gecko
  QC.Lic:
    repos:
      github.com/john-shepherdson/github-markup-scanner licensee:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-mustard-monkey.sh
        container: qc.lic_sleepy-orchid-eel
  QC.Met:
    repos:
      github.com/john-shepherdson/github-markup-scanner cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-scarlet-gecko.sh
        container: qc.met_gamy-ruby-millipede
  QC.Sty:
    repos:
      github.com/john-shepherdson/github-markup-scanner checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-xanthic-barnacle.sh
        container: qc.sty_scummy-alizarin-fish
      github.com/john-shepherdson/github-markup-scanner jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-green-cheetah.sh
        container: qc.sty_flabby-heliotrope-bison
  QC.Ver:
    repos:
      github.com/john-shepherdson/github-markup-scanner get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-viridian-pinscher.sh
        container: qc.ver_ready-russet-skunk
timeout: 5400
